name: connectivity_web
description: Flutter Web package, that allows you check internet status anytime or listen to change events, using the MobX lib as state management.
version: 0.1.0
author: Emanuel Braz (fastencoding@gmail.com)
homepage: https://github.com/emanuel-braz/connectivity_web

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
